[project]
name = "assassin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "charset-normalizer>=3.4.4",
    "keyboard>=0.13.5",
    "pydantic>=2.12.5",
    "pyinstaller>=6.18.0",
    "pyside6>=6.10.2",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.7",
]
